// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package upstash

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-upstash/sdk/go/upstash"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// 	"github.com/upstash/upstash-pulumi-provider/sdk/go/upstash"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		_, err := upstash.LookupKafkaTopic(ctx, &GetKafkaTopicArgs{
// 			TopicId: resource.Upstash_kafka_topic.ExampleKafkaTopic.Topic_id,
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func LookupKafkaTopic(ctx *pulumi.Context, args *LookupKafkaTopicArgs, opts ...pulumi.InvokeOption) (*LookupKafkaTopicResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv LookupKafkaTopicResult
	err := ctx.Invoke("upstash:index/getKafkaTopic:getKafkaTopic", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getKafkaTopic.
type LookupKafkaTopicArgs struct {
	// Unique Topic ID for requested kafka topic
	TopicId string `pulumi:"topicId"`
}

// A collection of values returned by getKafkaTopic.
type LookupKafkaTopicResult struct {
	// Cleanup policy will be used in the topic(compact or delete)
	CleanupPolicy string `pulumi:"cleanupPolicy"`
	// Id of the cluster this topic belongs to
	ClusterId string `pulumi:"clusterId"`
	// Creation time of the topic
	CreationTime int `pulumi:"creationTime"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// Max Message Size for the topic
	MaxMessageSize int `pulumi:"maxMessageSize"`
	// Whether multizone replication is enabled
	Multizone bool `pulumi:"multizone"`
	// Number of partitions the topic has
	Partitions int `pulumi:"partitions"`
	// Password to be used in authenticating to the cluster
	Password string `pulumi:"password"`
	// Region of the kafka topic. Possible values (may change) are: "eu-west-1", "us-east-1"
	Region string `pulumi:"region"`
	// REST Endpoint of the topic
	RestEndpoint string `pulumi:"restEndpoint"`
	// Max Retention Size of the topic
	RetentionSize int `pulumi:"retentionSize"`
	// Max Retention Time of the topic
	RetentionTime int `pulumi:"retentionTime"`
	// State of the topic (active or deleted)
	State string `pulumi:"state"`
	// TCP Endpoint of the topic
	TcpEndpoint string `pulumi:"tcpEndpoint"`
	// Unique Topic ID for requested kafka topic
	TopicId string `pulumi:"topicId"`
	// Name of the kafka topic
	TopicName string `pulumi:"topicName"`
	// Username to be used in authenticating to the cluster
	Username string `pulumi:"username"`
}

func LookupKafkaTopicOutput(ctx *pulumi.Context, args LookupKafkaTopicOutputArgs, opts ...pulumi.InvokeOption) LookupKafkaTopicResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupKafkaTopicResult, error) {
			args := v.(LookupKafkaTopicArgs)
			r, err := LookupKafkaTopic(ctx, &args, opts...)
			var s LookupKafkaTopicResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupKafkaTopicResultOutput)
}

// A collection of arguments for invoking getKafkaTopic.
type LookupKafkaTopicOutputArgs struct {
	// Unique Topic ID for requested kafka topic
	TopicId pulumi.StringInput `pulumi:"topicId"`
}

func (LookupKafkaTopicOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupKafkaTopicArgs)(nil)).Elem()
}

// A collection of values returned by getKafkaTopic.
type LookupKafkaTopicResultOutput struct{ *pulumi.OutputState }

func (LookupKafkaTopicResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupKafkaTopicResult)(nil)).Elem()
}

func (o LookupKafkaTopicResultOutput) ToLookupKafkaTopicResultOutput() LookupKafkaTopicResultOutput {
	return o
}

func (o LookupKafkaTopicResultOutput) ToLookupKafkaTopicResultOutputWithContext(ctx context.Context) LookupKafkaTopicResultOutput {
	return o
}

// Cleanup policy will be used in the topic(compact or delete)
func (o LookupKafkaTopicResultOutput) CleanupPolicy() pulumi.StringOutput {
	return o.ApplyT(func(v LookupKafkaTopicResult) string { return v.CleanupPolicy }).(pulumi.StringOutput)
}

// Id of the cluster this topic belongs to
func (o LookupKafkaTopicResultOutput) ClusterId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupKafkaTopicResult) string { return v.ClusterId }).(pulumi.StringOutput)
}

// Creation time of the topic
func (o LookupKafkaTopicResultOutput) CreationTime() pulumi.IntOutput {
	return o.ApplyT(func(v LookupKafkaTopicResult) int { return v.CreationTime }).(pulumi.IntOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupKafkaTopicResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupKafkaTopicResult) string { return v.Id }).(pulumi.StringOutput)
}

// Max Message Size for the topic
func (o LookupKafkaTopicResultOutput) MaxMessageSize() pulumi.IntOutput {
	return o.ApplyT(func(v LookupKafkaTopicResult) int { return v.MaxMessageSize }).(pulumi.IntOutput)
}

// Whether multizone replication is enabled
func (o LookupKafkaTopicResultOutput) Multizone() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupKafkaTopicResult) bool { return v.Multizone }).(pulumi.BoolOutput)
}

// Number of partitions the topic has
func (o LookupKafkaTopicResultOutput) Partitions() pulumi.IntOutput {
	return o.ApplyT(func(v LookupKafkaTopicResult) int { return v.Partitions }).(pulumi.IntOutput)
}

// Password to be used in authenticating to the cluster
func (o LookupKafkaTopicResultOutput) Password() pulumi.StringOutput {
	return o.ApplyT(func(v LookupKafkaTopicResult) string { return v.Password }).(pulumi.StringOutput)
}

// Region of the kafka topic. Possible values (may change) are: "eu-west-1", "us-east-1"
func (o LookupKafkaTopicResultOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v LookupKafkaTopicResult) string { return v.Region }).(pulumi.StringOutput)
}

// REST Endpoint of the topic
func (o LookupKafkaTopicResultOutput) RestEndpoint() pulumi.StringOutput {
	return o.ApplyT(func(v LookupKafkaTopicResult) string { return v.RestEndpoint }).(pulumi.StringOutput)
}

// Max Retention Size of the topic
func (o LookupKafkaTopicResultOutput) RetentionSize() pulumi.IntOutput {
	return o.ApplyT(func(v LookupKafkaTopicResult) int { return v.RetentionSize }).(pulumi.IntOutput)
}

// Max Retention Time of the topic
func (o LookupKafkaTopicResultOutput) RetentionTime() pulumi.IntOutput {
	return o.ApplyT(func(v LookupKafkaTopicResult) int { return v.RetentionTime }).(pulumi.IntOutput)
}

// State of the topic (active or deleted)
func (o LookupKafkaTopicResultOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v LookupKafkaTopicResult) string { return v.State }).(pulumi.StringOutput)
}

// TCP Endpoint of the topic
func (o LookupKafkaTopicResultOutput) TcpEndpoint() pulumi.StringOutput {
	return o.ApplyT(func(v LookupKafkaTopicResult) string { return v.TcpEndpoint }).(pulumi.StringOutput)
}

// Unique Topic ID for requested kafka topic
func (o LookupKafkaTopicResultOutput) TopicId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupKafkaTopicResult) string { return v.TopicId }).(pulumi.StringOutput)
}

// Name of the kafka topic
func (o LookupKafkaTopicResultOutput) TopicName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupKafkaTopicResult) string { return v.TopicName }).(pulumi.StringOutput)
}

// Username to be used in authenticating to the cluster
func (o LookupKafkaTopicResultOutput) Username() pulumi.StringOutput {
	return o.ApplyT(func(v LookupKafkaTopicResult) string { return v.Username }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupKafkaTopicResultOutput{})
}
