// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package upstash

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-upstash/sdk/go/upstash"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// 	"github.com/upstash/upstash-pulumi-provider/sdk/go/upstash"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		_, err := upstash.LookupTeam(ctx, &GetTeamArgs{
// 			TeamId: resource.Upstash_team.ExampleTeam.Team_id,
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func LookupTeam(ctx *pulumi.Context, args *LookupTeamArgs, opts ...pulumi.InvokeOption) (*LookupTeamResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv LookupTeamResult
	err := ctx.Invoke("upstash:index/getTeam:getTeam", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getTeam.
type LookupTeamArgs struct {
	// Unique Cluster ID for requested cluster
	TeamId string `pulumi:"teamId"`
}

// A collection of values returned by getTeam.
type LookupTeamResult struct {
	// Whether Credit card info is copied or not
	CopyCc bool `pulumi:"copyCc"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// Unique Cluster ID for requested cluster
	TeamId string `pulumi:"teamId"`
	// Members of the team. Email addresses are given as the keys with their roles as the values.
	TeamMembers map[string]string `pulumi:"teamMembers"`
	// Name of the team
	TeamName string `pulumi:"teamName"`
}

func LookupTeamOutput(ctx *pulumi.Context, args LookupTeamOutputArgs, opts ...pulumi.InvokeOption) LookupTeamResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupTeamResult, error) {
			args := v.(LookupTeamArgs)
			r, err := LookupTeam(ctx, &args, opts...)
			var s LookupTeamResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupTeamResultOutput)
}

// A collection of arguments for invoking getTeam.
type LookupTeamOutputArgs struct {
	// Unique Cluster ID for requested cluster
	TeamId pulumi.StringInput `pulumi:"teamId"`
}

func (LookupTeamOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupTeamArgs)(nil)).Elem()
}

// A collection of values returned by getTeam.
type LookupTeamResultOutput struct{ *pulumi.OutputState }

func (LookupTeamResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupTeamResult)(nil)).Elem()
}

func (o LookupTeamResultOutput) ToLookupTeamResultOutput() LookupTeamResultOutput {
	return o
}

func (o LookupTeamResultOutput) ToLookupTeamResultOutputWithContext(ctx context.Context) LookupTeamResultOutput {
	return o
}

// Whether Credit card info is copied or not
func (o LookupTeamResultOutput) CopyCc() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupTeamResult) bool { return v.CopyCc }).(pulumi.BoolOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupTeamResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTeamResult) string { return v.Id }).(pulumi.StringOutput)
}

// Unique Cluster ID for requested cluster
func (o LookupTeamResultOutput) TeamId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTeamResult) string { return v.TeamId }).(pulumi.StringOutput)
}

// Members of the team. Email addresses are given as the keys with their roles as the values.
func (o LookupTeamResultOutput) TeamMembers() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupTeamResult) map[string]string { return v.TeamMembers }).(pulumi.StringMapOutput)
}

// Name of the team
func (o LookupTeamResultOutput) TeamName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTeamResult) string { return v.TeamName }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupTeamResultOutput{})
}
