// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Upstash
{
    public static class GetQStashTopic
    {
        public static Task<GetQStashTopicResult> InvokeAsync(GetQStashTopicArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetQStashTopicResult>("upstash:index/getQStashTopic:getQStashTopic", args ?? new GetQStashTopicArgs(), options.WithDefaults());

        public static Output<GetQStashTopicResult> Invoke(GetQStashTopicInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetQStashTopicResult>("upstash:index/getQStashTopic:getQStashTopic", args ?? new GetQStashTopicInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetQStashTopicArgs : Pulumi.InvokeArgs
    {
        [Input("topicId", required: true)]
        public string TopicId { get; set; } = null!;

        public GetQStashTopicArgs()
        {
        }
    }

    public sealed class GetQStashTopicInvokeArgs : Pulumi.InvokeArgs
    {
        [Input("topicId", required: true)]
        public Input<string> TopicId { get; set; } = null!;

        public GetQStashTopicInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetQStashTopicResult
    {
        public readonly ImmutableArray<ImmutableDictionary<string, string>> Endpoints;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly string TopicId;

        [OutputConstructor]
        private GetQStashTopicResult(
            ImmutableArray<ImmutableDictionary<string, string>> endpoints,

            string id,

            string name,

            string topicId)
        {
            Endpoints = endpoints;
            Id = id;
            Name = name;
            TopicId = topicId;
        }
    }
}
