// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Upstash.Upstash
{
    public static class GetTeam
    {
        /// <summary>
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Upstash = Pulumi.Upstash;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var teamData = Output.Create(Upstash.GetTeam.InvokeAsync(new Upstash.GetTeamArgs
        ///         {
        ///             TeamId = resource.Upstash_team.ExampleTeam.Team_id,
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetTeamResult> InvokeAsync(GetTeamArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetTeamResult>("upstash:index/getTeam:getTeam", args ?? new GetTeamArgs(), options.WithDefaults());

        /// <summary>
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Upstash = Pulumi.Upstash;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var teamData = Output.Create(Upstash.GetTeam.InvokeAsync(new Upstash.GetTeamArgs
        ///         {
        ///             TeamId = resource.Upstash_team.ExampleTeam.Team_id,
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Output<GetTeamResult> Invoke(GetTeamInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetTeamResult>("upstash:index/getTeam:getTeam", args ?? new GetTeamInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetTeamArgs : Pulumi.InvokeArgs
    {
        [Input("teamId", required: true)]
        public string TeamId { get; set; } = null!;

        public GetTeamArgs()
        {
        }
    }

    public sealed class GetTeamInvokeArgs : Pulumi.InvokeArgs
    {
        [Input("teamId", required: true)]
        public Input<string> TeamId { get; set; } = null!;

        public GetTeamInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetTeamResult
    {
        public readonly bool CopyCc;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string TeamId;
        public readonly ImmutableDictionary<string, string> TeamMembers;
        public readonly string TeamName;

        [OutputConstructor]
        private GetTeamResult(
            bool copyCc,

            string id,

            string teamId,

            ImmutableDictionary<string, string> teamMembers,

            string teamName)
        {
            CopyCc = copyCc;
            Id = id;
            TeamId = teamId;
            TeamMembers = teamMembers;
            TeamName = teamName;
        }
    }
}
