# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .get_kafka_cluster import *
from .get_kafka_topic import *
from .get_redis_database import *
from .get_team import *
from .kafka_cluster import *
from .kafka_topic import *
from .provider import *
from .redis_database import *
from .team import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import upstash_upstash.config as __config
    config = __config
else:
    config = _utilities.lazy_import('upstash_upstash.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "upstash",
  "mod": "index/kafkaCluster",
  "fqn": "upstash_upstash",
  "classes": {
   "upstash:index/kafkaCluster:KafkaCluster": "KafkaCluster"
  }
 },
 {
  "pkg": "upstash",
  "mod": "index/kafkaTopic",
  "fqn": "upstash_upstash",
  "classes": {
   "upstash:index/kafkaTopic:KafkaTopic": "KafkaTopic"
  }
 },
 {
  "pkg": "upstash",
  "mod": "index/redisDatabase",
  "fqn": "upstash_upstash",
  "classes": {
   "upstash:index/redisDatabase:RedisDatabase": "RedisDatabase"
  }
 },
 {
  "pkg": "upstash",
  "mod": "index/team",
  "fqn": "upstash_upstash",
  "classes": {
   "upstash:index/team:Team": "Team"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "upstash",
  "token": "pulumi:providers:upstash",
  "fqn": "upstash_upstash",
  "class": "Provider"
 }
]
"""
)
