// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as upstash from "@pulumi/upstash";
 *
 * const clusterData = upstash.getKafkaCluster({
 *     clusterId: resource.upstash_kafka_cluster.exampleCluster.cluster_id,
 * });
 * ```
 */
export function getKafkaCluster(args: GetKafkaClusterArgs, opts?: pulumi.InvokeOptions): Promise<GetKafkaClusterResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("upstash:index/getKafkaCluster:getKafkaCluster", {
        "clusterId": args.clusterId,
    }, opts);
}

/**
 * A collection of arguments for invoking getKafkaCluster.
 */
export interface GetKafkaClusterArgs {
    clusterId: string;
}

/**
 * A collection of values returned by getKafkaCluster.
 */
export interface GetKafkaClusterResult {
    readonly clusterId: string;
    readonly clusterName: string;
    readonly creationTime: number;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly maxMessageSize: number;
    readonly maxMessagesPerSecond: number;
    readonly maxPartitions: number;
    readonly maxRetentionSize: number;
    readonly maxRetentionTime: number;
    readonly multizone: boolean;
    readonly password: string;
    readonly region: string;
    readonly restEndpoint: string;
    readonly state: string;
    readonly tcpEndpoint: string;
    readonly type: string;
    readonly username: string;
}

export function getKafkaClusterOutput(args: GetKafkaClusterOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetKafkaClusterResult> {
    return pulumi.output(args).apply(a => getKafkaCluster(a, opts))
}

/**
 * A collection of arguments for invoking getKafkaCluster.
 */
export interface GetKafkaClusterOutputArgs {
    clusterId: pulumi.Input<string>;
}
