// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getQStashScheduleV2(args: GetQStashScheduleV2Args, opts?: pulumi.InvokeOptions): Promise<GetQStashScheduleV2Result> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("upstash:index/getQStashScheduleV2:getQStashScheduleV2", {
        "body": args.body,
        "callback": args.callback,
        "delay": args.delay,
        "header": args.header,
        "retries": args.retries,
        "scheduleId": args.scheduleId,
    }, opts);
}

/**
 * A collection of arguments for invoking getQStashScheduleV2.
 */
export interface GetQStashScheduleV2Args {
    body?: string;
    callback?: string;
    delay?: string;
    header?: string;
    retries?: number;
    scheduleId: string;
}

/**
 * A collection of values returned by getQStashScheduleV2.
 */
export interface GetQStashScheduleV2Result {
    readonly body?: string;
    readonly callback?: string;
    readonly createdAt: number;
    readonly cron: string;
    readonly delay?: string;
    readonly destination: string;
    readonly header?: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly method: string;
    readonly retries?: number;
    readonly scheduleId: string;
}

export function getQStashScheduleV2Output(args: GetQStashScheduleV2OutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetQStashScheduleV2Result> {
    return pulumi.output(args).apply(a => getQStashScheduleV2(a, opts))
}

/**
 * A collection of arguments for invoking getQStashScheduleV2.
 */
export interface GetQStashScheduleV2OutputArgs {
    body?: pulumi.Input<string>;
    callback?: pulumi.Input<string>;
    delay?: pulumi.Input<string>;
    header?: pulumi.Input<string>;
    retries?: pulumi.Input<number>;
    scheduleId: pulumi.Input<string>;
}
