// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getQStashTopic(args: GetQStashTopicArgs, opts?: pulumi.InvokeOptions): Promise<GetQStashTopicResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("upstash:index/getQStashTopic:getQStashTopic", {
        "topicId": args.topicId,
    }, opts);
}

/**
 * A collection of arguments for invoking getQStashTopic.
 */
export interface GetQStashTopicArgs {
    topicId: string;
}

/**
 * A collection of values returned by getQStashTopic.
 */
export interface GetQStashTopicResult {
    readonly endpoints: {[key: string]: string}[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly topicId: string;
}

export function getQStashTopicOutput(args: GetQStashTopicOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetQStashTopicResult> {
    return pulumi.output(args).apply(a => getQStashTopic(a, opts))
}

/**
 * A collection of arguments for invoking getQStashTopic.
 */
export interface GetQStashTopicOutputArgs {
    topicId: pulumi.Input<string>;
}
