// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export * from "./getRedisDatabase";
export * from "./provider";
export * from "./redisDatabase";

// Export sub-modules:
import * as config from "./config";

export {
    config,
};

// Import resources to register:
import { RedisDatabase } from "./redisDatabase";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "upstash:index/redisDatabase:RedisDatabase":
                return new RedisDatabase(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("upstash", "index/redisDatabase", _module)

import { Provider } from "./provider";

pulumi.runtime.registerResourcePackage("upstash", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:upstash") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
