# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'GetQStashTopicResult',
    'AwaitableGetQStashTopicResult',
    'get_q_stash_topic',
    'get_q_stash_topic_output',
]

@pulumi.output_type
class GetQStashTopicResult:
    """
    A collection of values returned by getQStashTopic.
    """
    def __init__(__self__, endpoints=None, id=None, name=None, topic_id=None):
        if endpoints and not isinstance(endpoints, list):
            raise TypeError("Expected argument 'endpoints' to be a list")
        pulumi.set(__self__, "endpoints", endpoints)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if topic_id and not isinstance(topic_id, str):
            raise TypeError("Expected argument 'topic_id' to be a str")
        pulumi.set(__self__, "topic_id", topic_id)

    @property
    @pulumi.getter
    def endpoints(self) -> Sequence[Mapping[str, str]]:
        return pulumi.get(self, "endpoints")

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter
    def name(self) -> str:
        return pulumi.get(self, "name")

    @property
    @pulumi.getter(name="topicId")
    def topic_id(self) -> str:
        return pulumi.get(self, "topic_id")


class AwaitableGetQStashTopicResult(GetQStashTopicResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetQStashTopicResult(
            endpoints=self.endpoints,
            id=self.id,
            name=self.name,
            topic_id=self.topic_id)


def get_q_stash_topic(topic_id: Optional[str] = None,
                      opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetQStashTopicResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['topicId'] = topic_id
    if opts is None:
        opts = pulumi.InvokeOptions()
    if opts.version is None:
        opts.version = _utilities.get_version()
        if opts.plugin_download_url is None:
            opts.plugin_download_url = _utilities.get_plugin_download_url()
    __ret__ = pulumi.runtime.invoke('upstash:index/getQStashTopic:getQStashTopic', __args__, opts=opts, typ=GetQStashTopicResult).value

    return AwaitableGetQStashTopicResult(
        endpoints=__ret__.endpoints,
        id=__ret__.id,
        name=__ret__.name,
        topic_id=__ret__.topic_id)


@_utilities.lift_output_func(get_q_stash_topic)
def get_q_stash_topic_output(topic_id: Optional[pulumi.Input[str]] = None,
                             opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetQStashTopicResult]:
    """
    Use this data source to access information about an existing resource.
    """
    ...
